name: IRR updater

on:
  schedule:
  - cron: '*/15 * * * *'
  
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update lists
        run: ./run.sh
          
      - name: Commit files if changed
        run: ./commit.sh ${{ secrets.GITHUB_TOKEN }} "sources/ README.md"